# Generated by Django 4.1.7 on 2023-04-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_developer',
            field=models.BooleanField(default=False),
        ),
    ]
