# Generated by Django 4.1.7 on 2023-04-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0014_alter_developer_user'),
        ('accounts', '0002_useraccount_is_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='purchased_developers',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='purchased_developers',
            field=models.ManyToManyField(to='developers.developer'),
        ),
    ]
