# Generated by Django 4.1.7 on 2023-04-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0014_alter_developer_user'),
        ('accounts', '0003_remove_useraccount_purchased_developers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='purchased_developers',
            field=models.ManyToManyField(blank=True, to='developers.developer'),
        ),
    ]
