# Generated by Django 4.1.7 on 2023-04-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_alter_contactus_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'ContactUs'},
        ),
    ]
