# Generated by Django 4.1.7 on 2023-03-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_rename_name_developer_profile_name_developer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
