# Generated by Django 4.1.7 on 2023-03-28 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='developers.post'),
        ),
    ]
