# Generated by Django 4.1.7 on 2023-04-02 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0004_developer_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='posts',
        ),
    ]
