# Generated by Django 4.1.7 on 2023-04-09 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('developers', '0005_remove_developer_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='developer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
