# Generated by Django 4.1.7 on 2023-04-09 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0007_remove_developer_user_developer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='image_url',
        ),
    ]
