# Generated by Django 4.1.7 on 2023-04-09 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('developers', '0008_remove_developer_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='username',
        ),
        migrations.AddField(
            model_name='developer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
