# Generated by Django 4.1.7 on 2023-04-09 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0011_alter_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
